services:
  app:
    image: 'rides-service:latest'
    build:
      dockerfile: Dockerfile
    container_name: rides_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - microservices-network
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  db:
    image: postgres:latest
    container_name: rides_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - microservices-network
    volumes:
      - /var/lib/docker/volumes/rides-db:/var/lib/postgresql/data

networks:
  microservices-network:
    external: true