services:
  rides_app:
    image: 'rides-service:latest'
    build:
      dockerfile: Dockerfile
    container_name: rides-service
    depends_on:
      - rides_db
    ports:
      - "8083:8080"
    networks:
      - microservices-network
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  rides_db:
    image: postgres:latest
    container_name: ridedb-service
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    networks:
      - microservices-network
    volumes:
      - /var/lib/docker/volumes/rides-db:/var/lib/postgresql/data

networks:
  microservices-network:
    external: true